In [1]:
!pip install numpy

In [2]:
import numpy as np

## create array using numpy
## create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [6]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [7]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [4]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.random.rand(2,3)

array([[0.17457925, 0.72303544, 0.6251765 ],
       [0.94130655, 0.29797047, 0.63021955]])

In [10]:
np.random.randint(1,10,(2,3))

array([[2, 4, 5],
       [2, 5, 5]], dtype=int32)

In [12]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
arr=np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape: ",arr.shape)
print("Number of dimensions: ",arr.ndim)
print("Size (number of elements): ", arr.size)
print("data type: ", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
data type:  int64
Item size (in bytes):  8


In [15]:
### Numpy vectorized Operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element wise addition
print("Addition: ",arr1+arr2)

## Element wise subtraction
print("Subtraction: ",arr1-arr2)

## Element wise multiplication
print("Multiplication: ",arr1*arr2)

## Elemtn wise division
print("Division: ",arr1 / arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [ ]:
## Universal functions
arr=np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))

## sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [18]:
## Slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: ",arr)

Array:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
arr[0][0]
print(arr[0:2,1:])

[[2 3 4]
 [6 7 8]]


In [25]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [28]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [29]:
## Modify array elements

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [30]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [31]:
### Statistical concepts -- Normalization
data=np.array([1,2,3,4,5])

# Calculate the mean and standard deviation

mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data

normalized_data = (data - mean) / std_dev
print("Normalized data: ",normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [32]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean=np.mean(data)
print("Mean: ",mean)

# Median
median =  np.median(data)
print("Median: ",median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation: ", std_dev)

# Variance
variance = np.var(data)
print("Variance: ",variance)

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [36]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>5) & (data<=8)]

array([6, 7, 8])