In [2]:
import numpy as np 
print(np.__version__)

2.4.2


In [ ]:
## this is normal list which gives duplicate same values after multiplication
my_list = [1,2,3]
my_list = my_list * 2
print(my_list)

[1, 2, 3, 1, 2, 3]


In [6]:
array = np.array([1,2,3])
print(array)
print(type(array))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
## multiply each value to array
print(array*2)

[2 4 6]


In [ ]:
## arr.ndim -  1D or 2D or ND array
array = np.array([[['A', 'B', 'C'], ['D','E', 'F'], ['G','H','I']],
                [['J', 'K', 'L'], ['M','N', 'O'], ['P','Q','R']]])
print(array.ndim)

3


In [ ]:
## shape - shape shows layer, rows and column for 3D array and row and column only for 2D array
print(array.shape)

(2, 3, 3)


In [ ]:
## accessing elements
print(array[0][0][0])  ## chain indexing
print(array[0,0,0]) ## same result as previous one

A
A


In [19]:
print(array[0,1,1])

E


In [21]:
print(array[0,2,1])

H


In [24]:
word = array[0,0,0] + array[0,2,1] + array[0,1,2]
print(word)

AHF


In [35]:
## slicing - array[start:end:step]
array = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])

print(array[0])
print(array[1])
print(array[2])
print(array[3])

print(array[-2])
print(array[0:3])
print(array[1:4])

print(array[0:4:2])

print(array[::2])
print(array[::-2])



[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]
[ 9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 5  6  7  8]]


In [45]:
print(array)
print(array[:,0])
print(array[:,1])
print(array[:,2])
print(array[:,3])

print(array[:,0:3])
print(array[:,1:4])

print(array[:,::2])

print(array[:,1::2])
print(array)
print(array[:,0])
print(array[:,1])
print(array[:,2])
print(array[:,3])

print(array[:,0:3])
print(array[:,1:4])

print(array[:,::2])

print(array[:,1::-2])

print(array[0:2,0:2])



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]
[ 4  8 12 16]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]
[ 4  8 12 16]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[ 2]
 [ 6]
 [10]
 [14]]
[[1 2]
 [5 6]]


In [48]:
## scalar arithmetic
array = np.array([1,2,3])
print(array+1)
print(array-2)
print(array*3)
print(array/4)
print(array**5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [54]:
## Vectorized Math
array = np.array([8,2.5,7])
print(np.sqrt(array))
print(np.round(array))
print(np.floor(array))
print(np.ceil(array))
print(np.pi)

[2.82842712 1.58113883 2.64575131]
[8. 2. 7.]
[8. 2. 7.]
[8. 3. 7.]
3.141592653589793


In [55]:
radii = np.array([1,2,3])
print(np.pi * (radii**2))

[ 3.14159265 12.56637061 28.27433388]


In [58]:
## Elementwise arithmetic
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [ ]:
## Comparision Operators
scores = np.array([91,55,100,73,82,64])
print(scores == 100)
print(scores >= 60)

[False False  True False False False]
[ True False  True  True  True  True]


In [63]:
scores[scores < 60] = 0
print(scores)

[ 91   0 100  73  82  64]


After Broadcasting
array1 expands vertically
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

Shape becomes:

(4,4)
array2 expands horizontally
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]

Shape becomes:

(4,4)

Now, element wise addition

In [ ]:
## Broadcasting - Broadcasting in NumPy is a mechanism that allows arrays of different shapes 
#                   to perform element-wise operations without explicitly reshaping them and 
#                   virtually expanding dimensions by matching the larger array's shape
# Same → OK
# One is 1 → OK
# Different and none is 1 → ERROR

# Broadcasting works when each dimension pair is either:
# equal
# or one of them is 1

# (2,3) &(2,3) - Valid → element-wise operation.
# (2,3) & (1,3) - broadcast result - (2,3)
# (2,3) & (3,) -> (2,3) & (1,3) broadcast result - (2,3)
# (1,4) & (4,1) broadcast result - (4,4)
# (3,) & (2,) (1,3) & (1,2) broadcast not possible

array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])
print(array1.shape)
print(array2.shape)
print(array1)
print(array2)
print(array1+array2)



(1, 4)
(4, 1)
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [74]:
array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [94]:
## aggregate functions function_name(array, axis=0/1/None)

a = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
print(np.sum(a))       
print(np.sum(a, axis=0))  #(sum of columns) 
print(np.sum(a,axis=1))  #(sum of rows)
print(np.prod(a))
print(np.prod(a, axis=0))  
print(np.prod(a,axis=1)) 

55
[ 7  9 11 13 15]
[15 40]
3628800
[ 6 14 24 36 50]
[  120 30240]


In [ ]:
print(np.min(a))
print(np.max(a,axis=1))
print(np.argmin(a))
print(np.argmax(a))

1
[ 6  7  8  9 10]
0
9


In [ ]:
print(np.mean(a))
print(np.median(a))
print(np.average(a))

5.5
5.5
5.5


In [89]:
print(np.std(a))
print(np.var(a))

2.8722813232690143
8.25


In [90]:
print(np.cumsum(a))
print(np.cumprod(a))

[ 1  3  6 10 15 21 28 36 45 55]
[      1       2       6      24     120     720    5040   40320  362880
 3628800]


In [91]:
print(np.all(a))
print(np.any(a))

True
True


In [95]:
print(np.ptp(a))    # peat to peak - ptp = max -min
print(np.trace(a))  # Main Diagonal(top-left → bottom-right) (1,7)  

9
8


In [104]:
ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])

teenagers = ages[ages < 18]
adults = ages[(ages >= 18) & (ages < 65)]
seniors = ages[ages >= 65]

evens = ages[ages % 2 == 0]
odds = ages[ages % 2 != 0]

print(teenagers)
print(adults)
print(seniors)
print(evens)
print(odds)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]


In [ ]:
## np.where(condition, value_if_true, value_if_false)

adults = np.where(ages >= 18, ages,0)
print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


In [ ]:
## Creates a random number generator (RNG) object. New of generatoting random numbers in numpy
## (instead of np.random.randint)
## seed=1 ensures reproducibility: every time you run this, you get the same random numbers.
## Without a seed, you would get different numbers each run.
rng = np.random.default_rng(seed=1)
print(rng.integers(low=1, high=7, size=5))

[3 4 5 6 1]


In [ ]:
## np.random.uniform(low, high) generates a random floating-point number in the interval [low, high).
print(np.random.uniform(low=1, high=1, size=3))
print(np.random.uniform(low=1, high=1, size=(3,2)))  # size=(3,2) is dimension

[1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [117]:
array = np.array([1,2,3,4,5])
rng = np.random.default_rng()
rng.shuffle(array)
print(array)

[5 4 1 2 3]


In [121]:
fruits = ["apple", "banana", "kiwi", "mango", "coconut", "pear"]
fruits = rng.choice(fruits, size=3)
print(fruits)
fruits = rng.choice(fruits, size=(3,3))
print(fruits)

['coconut' 'apple' 'coconut']
[['apple' 'apple' 'coconut']
 ['coconut' 'coconut' 'coconut']
 ['apple' 'apple' 'coconut']]
