In [31]:
import numpy as np 
print(np.__version__)

2.4.2


In [ ]:
## this is normal list which gives duplicate same values after multiplication
my_list = [1,2,3]
my_list = my_list * 2
print(my_list)

[1, 2, 3, 1, 2, 3]


In [4]:
array = np.array([1,2,3])
print(array)
print(type(array))
print(array.dtype)

[1 2 3]
<class 'numpy.ndarray'>
int64


In [ ]:
## multiply each value to array
print(array*2)

[2 4 6]


In [ ]:
## arr.ndim -  1D or 2D or ND array
array = np.array([[['A', 'B', 'C'], ['D','E', 'F'], ['G','H','I']],
                [['J', 'K', 'L'], ['M','N', 'O'], ['P','Q','R']]])
print(array.ndim)

3


In [ ]:
## shape - shape shows layer, rows and column for 3D array and row and column only for 2D array
print(array.shape)

(2, 3, 3)


In [ ]:
## accessing elements
print(array[0][0][0])  ## chain indexing
print(array[0,0,0]) ## same result as previous one

A
A


In [19]:
print(array[0,1,1])

E


In [21]:
print(array[0,2,1])

H


In [24]:
word = array[0,0,0] + array[0,2,1] + array[0,1,2]
print(word)

AHF


In [35]:
## slicing - array[start:end:step]
array = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])

print(array[0])
print(array[1])
print(array[2])
print(array[3])

print(array[-2])
print(array[0:3])
print(array[1:4])

print(array[0:4:2])

print(array[::2])
print(array[::-2])



[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]
[ 9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 5  6  7  8]]


In [45]:
print(array)
print(array[:,0])
print(array[:,1])
print(array[:,2])
print(array[:,3])

print(array[:,0:3])
print(array[:,1:4])

print(array[:,::2])

print(array[:,1::2])
print(array)
print(array[:,0])
print(array[:,1])
print(array[:,2])
print(array[:,3])

print(array[:,0:3])
print(array[:,1:4])

print(array[:,::2])

print(array[:,1::-2])

print(array[0:2,0:2])



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]
[ 4  8 12 16]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]
[ 4  8 12 16]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
[[ 2]
 [ 6]
 [10]
 [14]]
[[1 2]
 [5 6]]


In [48]:
## scalar arithmetic
array = np.array([1,2,3])
print(array+1)
print(array-2)
print(array*3)
print(array/4)
print(array**5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [54]:
## Vectorized Math
array = np.array([8,2.5,7])
print(np.sqrt(array))
print(np.round(array))
print(np.floor(array))
print(np.ceil(array))
print(np.pi)

[2.82842712 1.58113883 2.64575131]
[8. 2. 7.]
[8. 2. 7.]
[8. 3. 7.]
3.141592653589793


In [55]:
radii = np.array([1,2,3])
print(np.pi * (radii**2))

[ 3.14159265 12.56637061 28.27433388]


In [58]:
## Elementwise arithmetic
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [ ]:
## Comparision Operators
scores = np.array([91,55,100,73,82,64])
print(scores == 100)
print(scores >= 60)

[False False  True False False False]
[ True False  True  True  True  True]


In [63]:
scores[scores < 60] = 0
print(scores)

[ 91   0 100  73  82  64]


After Broadcasting
array1 expands vertically
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

Shape becomes:

(4,4)
array2 expands horizontally
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]

Shape becomes:

(4,4)

Now, element wise addition

In [ ]:
## Broadcasting - Broadcasting in NumPy is a mechanism that allows arrays of different shapes 
#                   to perform element-wise operations without explicitly reshaping them and 
#                   virtually expanding dimensions by matching the larger array's shape
# Same → OK
# One is 1 → OK
# Different and none is 1 → ERROR

# Broadcasting works when each dimension pair is either:
# equal
# or one of them is 1

# (2,3) &(2,3) - Valid → element-wise operation.
# (2,3) & (1,3) - broadcast result - (2,3)
# (2,3) & (3,) -> (2,3) & (1,3) broadcast result - (2,3)
# (1,4) & (4,1) broadcast result - (4,4)
# (3,) & (2,) (1,3) & (1,2) broadcast not possible

array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])
print(array1.shape)
print(array2.shape)
print(array1)
print(array2)
print(array1+array2)



(1, 4)
(4, 1)
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [74]:
array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [94]:
## aggregate functions function_name(array, axis=0/1/None)

a = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
print(np.sum(a))       
print(np.sum(a, axis=0))  #(sum of columns) 
print(np.sum(a,axis=1))  #(sum of rows)
print(np.prod(a))
print(np.prod(a, axis=0))  
print(np.prod(a,axis=1)) 

55
[ 7  9 11 13 15]
[15 40]
3628800
[ 6 14 24 36 50]
[  120 30240]


In [ ]:
print(np.min(a))
print(np.max(a,axis=1))
print(np.argmin(a))
print(np.argmax(a))

1
[ 6  7  8  9 10]
0
9


In [ ]:
print(np.mean(a))
print(np.median(a))
print(np.average(a))

5.5
5.5
5.5


In [89]:
print(np.std(a))
print(np.var(a))

2.8722813232690143
8.25


In [90]:
print(np.cumsum(a))
print(np.cumprod(a))

[ 1  3  6 10 15 21 28 36 45 55]
[      1       2       6      24     120     720    5040   40320  362880
 3628800]


In [91]:
print(np.all(a))
print(np.any(a))

True
True


In [95]:
print(np.ptp(a))    # peat to peak - ptp = max -min
print(np.trace(a))  # Main Diagonal(top-left → bottom-right) (1,7)  

9
8


In [104]:
ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])

teenagers = ages[ages < 18]
adults = ages[(ages >= 18) & (ages < 65)]
seniors = ages[ages >= 65]

evens = ages[ages % 2 == 0]
odds = ages[ages % 2 != 0]

print(teenagers)
print(adults)
print(seniors)
print(evens)
print(odds)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]
[21 17 19 65 39 15 99 19 21]


In [ ]:
## np.where(condition, value_if_true, value_if_false)

adults = np.where(ages >= 18, ages,0)
print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


In [ ]:
## Creates a random number generator (RNG) object. New of generatoting random numbers in numpy
## (instead of np.random.randint)
## seed=1 ensures reproducibility: every time you run this, you get the same random numbers.
## Without a seed, you would get different numbers each run.
rng = np.random.default_rng(seed=1)
print(rng.integers(low=1, high=7, size=5))

[3 4 5 6 1]


In [ ]:
## np.random.uniform(low, high) generates a random floating-point number in the interval [low, high).
print(np.random.uniform(low=1, high=1, size=3))
print(np.random.uniform(low=1, high=1, size=(3,2)))  # size=(3,2) is dimension

[1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [117]:
array = np.array([1,2,3,4,5])
rng = np.random.default_rng()
rng.shuffle(array)
print(array)

[5 4 1 2 3]


In [121]:
fruits = ["apple", "banana", "kiwi", "mango", "coconut", "pear"]
fruits = rng.choice(fruits, size=3)
print(fruits)
fruits = rng.choice(fruits, size=(3,3))
print(fruits)

['coconut' 'apple' 'coconut']
[['apple' 'apple' 'coconut']
 ['coconut' 'coconut' 'coconut']
 ['apple' 'apple' 'coconut']]


In [5]:
## arange() - Create arrays with regularly spaced values (like Python’s range)
## np.arange(start,stop,step)

arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [6]:
arr = np.arange(0,1,0.2)
print(arr)

[0.  0.2 0.4 0.6 0.8]


In [7]:
## linspace() - Create arrays with a fixed number of points between start and stop (inclusive)
## np.linspace(start,stop,num=5) - Useful when you want exactly N points, unlike arange which is step-based.
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
## zeros() - create an array filled with zeros
## np.zeros(shape, dtype=float) default float

arr = np.zeros(5)
print(arr)

arr2d = np.zeros((2,3))
print(arr2d)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
## ones - create an array filled with ones
## ## np.ones(shape, dtype=float) float by default

arr = np.ones(4)
print(arr)

arr2d = np.ones((3,2),dtype=int)
print(arr2d)

[1. 1. 1. 1.]
[[1 1]
 [1 1]
 [1 1]]


In [11]:
## eye() - create and identity matrix
## np.eye(N) - NxN identity matrix

i = np.eye(2)
print(i)

[[1. 0.]
 [0. 1.]]


In [13]:
## empty() - Create an array without initializing values (faster, but contains garbage values)
## np.empty(shape)

arr = np.empty((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
## full() - Create an array filled with a specific value
## np.full(shape,fill_value)
arr = np.full((3,4),6)
print(arr)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [ ]:
## random().rand() - Create arrays of random floats in [0,1)
## np.random.rand(shape1,shape2,....)

arr = np.random.rand(3)
print(arr)

arr2d = np.random.rand(3,5)
print(arr2d)

[0.79057617 0.08171702 0.70764686]
[[0.29019341 0.20072434 0.94199626 0.69258279 0.05735926]
 [0.05426577 0.85928605 0.84908708 0.93171172 0.29260622]
 [0.17310572 0.18624871 0.83291006 0.02367033 0.3088341 ]]


In [ ]:
## random.randint() - generate random integers in [low,high]
## np.random.randint(low,high,size)

arr = np.random.randint(3,10,size=(2,3))   # like rolling a die
print(arr)

[[4 6 3]
 [9 9 6]]


In [19]:
## Array attributes
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [21]:
# Returns the dimensions of the array as (rows, columns).
print("Shape:", arr.shape) 

# Total number of elements in the array.
print("Size:", arr.size)

#Number of dimensions (axes) in the array.
# 1D → [1,2,3], 2D → [[1,2],[3,4]] & 3D → cube-like structure
print("Dimensions:", arr.ndim)

# Shows the data type of elements stored in the array.
print("Data Type:", arr.dtype)

# Size of one element in bytes. each int64 element uses 8 bytes
print("Item Size:", arr.itemsize)

#Total memory used by the array in bytes.
print("Total Bytes:", arr.nbytes)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int64
Item Size: 8
Total Bytes: 48


In [ ]:
## Boolean indexing and fancy indexing
## Boolean indexing → Filter by condition
## Fancy indexing → Select by index positions

marks = np.array([45, 70, 55, 80, 30])

# Boolean indexing
passed = marks[marks >= 50]

# Fancy indexing
selected = marks[[0,3,4]]

print(passed)
print(selected)

[70 55 80]
[45 80 30]


In [23]:
## Basic array operations using universal functions (ufuncs)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


In [24]:
print(np.add(a,b))

[5 7 9]


In [25]:
print(np.subtract(a,b))

[-3 -3 -3]


In [26]:
print(np.multiply(a,b))

[ 4 10 18]


In [27]:
print(np.divide(a,b))

[0.25 0.4  0.5 ]


In [32]:
print(np.power(a,2))

[1 4 9]


In [33]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081]


In [34]:
print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692]


In [35]:
print(np.log(a))

[0.         0.69314718 1.09861229]


In [ ]:
## values are calculated in radians

print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]


In [38]:
## Without Vectorization (Slow)
result = []
for i in range(len(a)):
    result.append(a[i] + b[i])
print(result)

[np.int64(5), np.int64(7), np.int64(9)]


In [40]:
## With Vectorization (Fast)
result = a + b
print(result)

[5 7 9]


In [41]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

In [42]:
## Matrix Multiplication
## using @ operator
C = A @ B
print(C)

## using np.dot()

C = np.dot(A, B)
print(C)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Calculation:
[1 2]   [5 6]   [(1×5 + 2×7)  (1×6 + 2×8)]
[3 4] × [7 8] = [(3×5 + 4×7)  (3×6 + 4×8)]

In [43]:
## Transpose matrix - The transpose of a matrix swaps rows and columns. mxn becoms nxm after transpose

A = np.array([[1,2,3],
            [4,5,6]])
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
## Matrix Inverse - The inverse of a square matrix A is a matirx A^(-1)
## AA^(-1) = I

A = np.array([[1,2],
                [3,4]])
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [45]:
## Determinant - The determinant is a value that indicates properties of a matrix.
A = np.array([[1,2],
                [3,4]])
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [46]:
## Eigen Values and Eigen Vectors
A = np.array([[4, -2],
              [1, 1]])

np.linalg.eig(A)

EigResult(eigenvalues=array([3., 2.]), eigenvectors=array([[0.89442719, 0.70710678],
       [0.4472136 , 0.70710678]]))

In [47]:
## Rank of a matrix - number of linearly independent rows or columns.
np.linalg.matrix_rank(A)

np.int64(2)

In [49]:
## Matrix Norm - Norm measures the size or magnitude of a matrix/vector.
np.linalg.norm(A)

np.float64(4.69041575982343)

In [50]:
## reshape() - Change the shape of an array without changing its data.

a = np.arange(6)
b=a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [51]:
## ravel() - Flattens a multi-dimensional array into 1-D array.
## Returns a view if possible (modifying it may affect original array).
b.ravel()

array([0, 1, 2, 3, 4, 5])

In [52]:
## flatten() - Also flattens into 1-D, but returns a copy. Safe for independent modifications

b.flatten()

array([0, 1, 2, 3, 4, 5])

In [55]:
## resize() - Change the shape of the array in-place. If new size > original, it fills with zeros.
a= np.arange(4)
a.resize(3,4)
print(a)

[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]


In [58]:
## swapaxes(a, axis1, axis2) - swaps two axes of an array
a = np.arange(12).reshape(3,4)
print(a)
np.swapaxes(a,0,1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [64]:
## concatenate() - Joins arrays along an existing axis.
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
x = np.concatenate((a,b), axis=0)  # along rows
x

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [65]:
y = np.concatenate((a,b), axis=1)  # along columns
y

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [66]:
## vstack() - Stack arrays vertically (row-wise).
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [67]:
## hstack() - Stack arrays horizontally (column-wise).
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [68]:
## stack() - np.stack((a,b), axis=0)  # new dimension added
np.stack((a,b), axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [69]:
## split()

x = np.arange(10)
np.split(x,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [70]:
np.hsplit(a, 2)  # split columns
np.vsplit(a, 2)  # split rows

[array([[1, 2]]), array([[3, 4]])]

In [71]:
a = np.array([1,2])
np.tile(a,3)

array([1, 2, 1, 2, 1, 2])

In [72]:
## np.random.randn() - Generates numbers from a standard normal distribution
## (mean = 0, standard deviation = 1).
np.random.randn(3)

array([ 0.04079636, -1.08516317,  1.5115525 ])

In [75]:
## np.random.choice() - Randomly selects elements from a list or array.
np.random.choice([10,20,30,40])
np.random.choice([1,2,3,4], size=3)

array([4, 3, 3])

In [76]:
## np.random.seed(42) - Sets a fixed starting point for random numbers so results are reproducible.
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [ ]:
## NumPy can generate numbers from many probability distributions.

In [ ]:
## All numbers have equal probability. 
np.random.uniform(0, 10, size=5)

array([5.98658484, 1.5601864 , 1.5599452 , 0.58083612, 8.66176146])

In [ ]:
## Normal Distribution also, gaussian distribution 
## np.random.normal(mean, standart deviation,size)
np.random.normal(0, 1, 5)

In [78]:
## Binomial Distribution - Represents number of successes in n trials.
## np.random.binomial(num of traila, probability of success)
np.random.binomial(10, 0.5, size=5)

array([5, 6, 2, 8, 7], dtype=int32)

In [80]:
## np.save() - Used to save a single NumPy array in binary (.npy) format.
arr = np.array([1,2,3,4,5])
np.save("data.npy",arr)

In [81]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.savez("arrays.npz", arr1=a, arr2=b)

In [82]:
## np.savetxt() - used to save in text format (.txt, or .csv)
arr = np.array([[1,2,3],
                [4,5,6]])
np.savetxt("data.txt",arr)

In [83]:
data = np.load("data.npy")
print(data)

[1 2 3 4 5]


In [84]:
data = np.load("arrays.npz")
print(data['arr1'])
print(data['arr2'])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [85]:
## np.loadtxt() - Used to load text files created with savetxt().
data = np.loadtxt("data.txt")

In [ ]:
data = np.loadtxt("data.csv", delimiter=",")

In [87]:
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

In [ ]:
## Ellipsis (...) is used in NumPy slicing to represent all remaining dimensions in a multi-dimensional array.
##I t is helpful when working with high-dimensional arrays so you don’t need to write many : symbols.
## arr[..., 1]
arr[:, :, 1]

## using ellipsis
arr[..., 1]

array([[2, 4],
       [6, 8]])

In [92]:
## np.take() - np.take() selects elements from an array using index values.
## np.take(array,indices)
arr = np.array([10,20,30,40,50])

np.take(arr, [0,2,4])



array([10, 30, 50])

In [93]:
arr = np.array([[1,2],[3,4]])

np.take(arr, [0], axis=1)

array([[1],
       [3]])

In [94]:
## np.put() - replaces values at specific indices.
## np.put(array, indices, values)
arr = np.array([10,20,30,40])

np.put(arr, [1,3], [99,88])

print(arr)

[10 99 30 88]


In [95]:
## np.choose() - selects elements from multiple arrays using an index array.
## np.choose(index_array, choices)
a = np.array([0,1,0,1])

choice1 = np.array([10,10,10,10])
choice2 = np.array([20,20,20,20])

np.choose(a, [choice1, choice2])

array([10, 20, 10, 20])

In [96]:
## np.extract() returns elements that satisfy a condition.
# # np.extract(condition, array)
arr = np.array([10,25,30,45,50])

np.extract(arr > 30, arr)


array([45, 50])

In [97]:
## np.compress() - selects elements along an axis using a Boolean mask.
arr = np.array([[10,20],[30,40],[50,60]])

condition = [True, False, True]

np.compress(condition, arr, axis=0)

array([[10, 20],
       [50, 60]])

In [99]:
## np.isnan()  - checks whether elements in an array are NaN (Not a Number).
## np.isnan(array)
arr = np.array([10, np.nan, 30, np.nan])
np.isnan(arr)

array([False,  True, False,  True])

In [100]:
## np.nanmean() - calculates the mean (average) while ignoring NaN values.
arr = np.array([10, 20, np.nan, 40])
np.nanmean(arr)

np.float64(23.333333333333332)

In [101]:
## np.nansum() - calculates the sum of elements ignoring NaN values.
arr = np.array([5, np.nan, 10, 15])
np.nansum(arr)

np.float64(30.0)

In [102]:
##  np.nanstd() - calculates the standard deviation ignoring NaN values.
arr = np.array([2,4,6,np.nan])

np.nanstd(arr)

np.float64(1.632993161855452)

In [103]:
## np.ma.masked_array() creates a masked array where certain values are ignored (masked) during calculations.
## A mask is a Boolean array: True → value ignored False → value used
## np.ma.masked_array(data, mask)

data = np.array([10,20,30,40])
mask = [False, True, False, True]
m = np.ma.masked_array(data, mask)
print(m)


[10 -- 30 --]


In [105]:
## np.unique() - returns the unique elements of an array (removes duplicates).
## np.unique(array)
arr = np.array([3,1,2,3,4,2,1])
np.unique(arr)

array([1, 2, 3, 4])

In [106]:
## np.sort() - sorts elements of an array.
arr = np.array([5,2,8,1])
np.sort(arr)

array([1, 2, 5, 8])

In [107]:
arr = np.array([[3,1],[4,2]])
np.sort(arr, axis=1)

array([[1, 3],
       [2, 4]])

In [108]:
## np.argsort() - returns the indices that would sort the array.
arr = np.array([50,20,40,10])
np.argsort(arr)

array([3, 1, 2, 0])

In [109]:
## np.intersect1d() - Returns common elements between two arrays.
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])
np.intersect1d(a,b)

array([3, 4])

In [110]:
## np.setdiff1d() - Returns elements present in the first array but not in the second.
## np.setdiff1d(a,b)
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])
np.setdiff1d(a,b)


array([1, 2])

In [ ]:
## np.in1d() - Checks whether elements of one array exist in another array.
a = np.array([1,2,3,4])
b = np.array([2,4])
np.in1d(a,b)

In [113]:
## np.polyval() - Evaluates a polynomial at specific values.
## np.polyval(coefficients, x)
## 2x² + 3x + 1
np.polyval([2,3,1], 2)


np.int64(15)

In [114]:
## np.olyfit() - Fits a polynomial curve to data points.
## np.polyfit(x, y, degree)
## y = 2x + 0
x = np.array([1,2,3])
y = np.array([2,4,6])

np.polyfit(x,y,1)


array([2.00000000e+00, 2.52280859e-15])

In [115]:
## np.select() - selects values based on multiple conditions.
## np.select(condition_list, choice_list, default)
x = np.array([5,15,25])

conditions = [x < 10, x < 20]
choices = ["Low","Medium"]

np.select(conditions, choices, default="High")


array(['Low', 'Medium', 'High'], dtype='<U6')